language: python
python:
  - "3.8.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose pylint
# command to run tests
script: find . -name "*.py" | xargs pylint -E
