version: '2'
services:
  monitor-docker-slack:
    container_name: monitor-docker-slack
    image: denny/monitor-docker-slack
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SLACK_WEBHOOK_URL: "$SLACK_WEBHOOK_URL"
      MSG_PREFIX: "$MSG_PREFIX"
    restart: always
